name: Lint | Build | Deploy to Production

on:
  push:
    branches:
      - main

env:
  NODE_LTS_VERSION: 18
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }}
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }}
  TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  CLEARBIT_SECRET_KEY: ${{ secrets.CLEARBIT_SECRET_KEY }}
  HUNTERIO_API_KEY: ${{ secrets.HUNTERIO_API_KEY }}

jobs:
  lint_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node v${{ env.NODE_LTS_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true
          cache: "npm"

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          npm install

      - name: Install Vercel CLI
        run: |
          echo "Installing Vercel CLI..."
          npm install --global vercel@latest

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npm run lint

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: |
          echo "Building..."
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Production
        run: |
          echo "ðŸŽ‰ Deploying..."
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
